name: Docker Image CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        name: Docker Login
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag registry.nomis.cc/nomis/solana-score-api:${{ github.ref_name }} && docker push registry.nomis.cc/nomis/solana-score-api:${{ github.ref_name }}